### ISSUE TITLE
Add snippets into Gutenberg

### ISSUE THREAD

**Issue by davdebcom** [GreenTreeLabs/post-snippets#92]

**Comment by arnalyse** [comment]
Hi there, I'd just wanted to know, if there is any progress towards Post Snippets Gutenberg. Maybe I can help.

**Comment by davdebcom** [comment]
@arnalyse Not yet, still need to look into it. PR's are welcome!

**Comment by tdwesten** [comment]
@davdebcom any updates/plans to add Gutenberg support??

**Comment by GreenTreeLabs** [comment]
Hi @tdwesten, support for Gutenberg is scheduled for first quarter of 2020.
