### ISSUE TITLE
Using php functions causes an "Updating failed" error with the Gutenberg editor

### ISSUE THREAD

**Issue by outdooracorn** [GreenTreeLabs/post-snippets#94]
When I use a function in a PHP snippet I get an error "Updating failed" whenever I try and save or preview a post. The code works in that if I get the `id` of the post and go to the URL `https://example.com/?p=<id>&preview=true` it displays correctly with `hello_world`. I tried with the classic editor and that worked fine so it's just an issue with the Gutenburg editor. I tried using the paragraph, shortcode and classic blocks.

### PHP Code:

```
function hello_world(){
    return "hello_world";
}

echo hello_world();
```

### Image of PHP Code:
![image](https://user-images.githubusercontent.com/43674967/47162496-fb4bda80-d2eb-11e8-926f-cff1a36af433.png)

### Image of the Error Using the Shortcode Block:
![image](https://user-images.githubusercontent.com/43674967/47162632-3a7a2b80-d2ec-11e8-803a-2d84c3beec8d.png)

### Image of the Error Using the Classic Block:
![image](https://user-images.githubusercontent.com/43674967/47162751-7c0ad680-d2ec-11e8-9b93-066817194daa.png)

**Comment by davdebcom** [comment]
You are using Gutenberg which is still in alpha and in heavy development. I'll need to review the full implementation in Gutenberg soon, but it's not something I've done yet. Feel free to do further research and provide pull requests if you get to this before I do.
