### ISSUE TITLE
Failed to load plugin url: ...post-snippets/tinymce/langs/nl.js

### ISSUE THREAD

**Issue by davdebcom** [GreenTreeLabs/post-snippets#96]
Got one report of this error with WP5.0, didn't get it when testing myself, need to research:

Failed to load plugin url: …/wp-content/plugins/post-snippets/tinymce/langs/nl.js

**Comment by stkams** [comment]
Had the same issue. Downloaded the language pack from https://www.tiny.cloud/get-tiny/language-packages/ and added nl.js to wp-content/plugins/post-snippets/tinymce/langs/

**Comment by GreenTreeLabs** [comment]
Added all languages in 3.0.11
